In [6]:
# import os

# # Define the desired directory path
# desired_directory = r"C:\Users\jimrb\OneDrive\Documents\Python Scripts\Python for Data Science"

# # Get the current directory
# current_directory = os.getcwd()

# # Check if the current directory is different from the desired one
# if current_directory != desired_directory:
#     try:
#         # Change to the desired directory
#         os.chdir(desired_directory)
#         print(f"Changed directory to: {desired_directory}")
#     except changingerror as e:
#         print(f"Error changing directory: {e}")
# else:
#     print(f"Already in the desired directory: {desired_directory}")

In [7]:
import os
print(os.getcwd())

C:\Users\jimrb\OneDrive\Documents\MyProjects\mypython github


In [8]:
#Provides ways to work with large multidimensional arrays
import numpy as np
#Allows for further data manipulation and analysis
import pandas as pd
import matplotlib.pyplot as plt #plotting
import matplotlib.dates as mdates ## Styling dates
%matplotlib inline

import warnings
warnings.simplefilter("ignore")

# Numpy

In [9]:
#create numpy array
ll = [1,2,3,4,5]
npa1 = np.array(ll)
npa1

array([1, 2, 3, 4, 5])

In [10]:
#create array from 0-4
npa2 = np.arange(0,6)
npa2

array([0, 1, 2, 3, 4, 5])

In [11]:
#define a step
npa3 = np.arange(0,11,2)
npa3

array([ 0,  2,  4,  6,  8, 10])

# Matrices

In [12]:
#create a 4 matrix with 3 columns with all having a value of 1
mat1 = np.ones((4,3))
mat1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
#create a 4 row matrix with 3 columns with all having a value of 0
mat2 = np.zeros((4,3))
mat2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Random Matrices

In [14]:
# Random values between 0 and 50 as a matrix with 4r and 3c
mat3 = np.random.randint(0,50,(4,3))
mat3

array([[16, 20, 47],
       [42, 23, 44],
       [ 4, 14, 12],
       [49, 26, 27]])

In [15]:
#Generate 10 equally distanced values between 1 and 10
mat4 = np.linspace(1,10,10)
mat4

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# Reshape Arrays

In [16]:
# Create array with 12 values
mat6 = np.random.randint(0,50,12)
mat6

array([40, 11, 39,  2, 35, 33, 39, 29, 19, 42, 14, 44])

In [17]:
# Reshape to a 3 row 4 column array
mat6 = mat6.reshape(3,4)
mat6

array([[40, 11, 39,  2],
       [35, 33, 39, 29],
       [19, 42, 14, 44]])

In [18]:
# Reshape into a 3D array with 3 blocks, 2 rows, 2 columns
mat7 = mat6.reshape(3,2,2)
mat7

array([[[40, 11],
        [39,  2]],

       [[35, 33],
        [39, 29]],

       [[19, 42],
        [14, 44]]])

In [19]:
# Reshape into a 3D array with 2 blocks, 3 rows, 2 columns
mat8 = mat6.reshape(2,3,2)
mat8

array([[[40, 11],
        [39,  2],
        [35, 33]],

       [[39, 29],
        [19, 42],
        [14, 44]]])

In [20]:
# Get the value in the 2nd block, 3rd row and 1st column
mat8[0,0,0]

40

# Filter Array

In [21]:
# Provide a booliean array where values are above 20
print(mat6)
mat6 > 20

[[40 11 39  2]
 [35 33 39 29]
 [19 42 14 44]]


array([[ True, False,  True, False],
       [ True,  True,  True,  True],
       [False,  True, False,  True]])

In [22]:
# Return an array with just values over 20
mat6[mat6 > 20]

array([40, 39, 35, 33, 39, 29, 42, 44])

# Statistics Operations

In [23]:
mat5 = np.random.randint(0,100,50)
mat5
print("Mean: ", mat5.mean())
print("Standard Deviation: ", mat5.std())
print("Variance: ", mat5.var())
print("Min: ", mat5.min())
print("Max: ", mat5.max())

Mean:  48.52
Standard Deviation:  30.494091230925378
Variance:  929.8896
Min:  3
Max:  97


# The Seed Function

In [24]:
# Ensure that the random values are generated every run
np.random.seed(500)
mat9 = np.random.randint(0,50,10)
mat9

array([26,  1, 17, 14, 31,  8,  7, 13, 45, 17])

In [25]:
mat9

array([26,  1, 17, 14, 31,  8,  7, 13, 45, 17])

In [26]:
mat10 = np.random.randint(0,50,10)
mat10

array([17, 21, 41, 34, 42, 18, 19, 13, 38, 40])

In [27]:
mat10

array([17, 21, 41, 34, 42, 18, 19, 13, 38, 40])

# Pandas

# Read Data from a CSV

In [28]:
file_path = r"C:\Users\jimrb\OneDrive\Documents\MyProjects\mypython github\Datasets\Orders.csv"
def get_df_from_csv(file_path):
    try: #The code inside the try block is executed, and any exceptions that occur are caught and handled in the except block.
        df = pd.read_csv(file_path, index_col = 'Row ID')
    except FileNotFoundError:
        pass #In the except block, there is only a pass statement. This means that if a FileNotFoundError occurs, the code will essentially do nothing (i.e., it won't raise an error or perform any specific action).
    else:
        return df

In [30]:
df = pd.read_csv(file_path, index_col = 'Row ID')

if df is not None:
    print(df.head(10))
else:
    print("File not found.")

              Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
Row ID                                                                       
1       CA-2016-152156   8/11/2016  11/11/2016    Second Class    CG-12520   
2       CA-2016-152156   8/11/2016  11/11/2016    Second Class    CG-12520   
3       CA-2016-138688  12/06/2016  16/06/2016    Second Class    DV-13045   
4       US-2015-108966  11/10/2015  18/10/2015  Standard Class    SO-20335   
5       US-2015-108966  11/10/2015  18/10/2015  Standard Class    SO-20335   
6       CA-2014-115812   9/06/2014  14/06/2014  Standard Class    BH-11710   
7       CA-2014-115812   9/06/2014  14/06/2014  Standard Class    BH-11710   
8       CA-2014-115812   9/06/2014  14/06/2014  Standard Class    BH-11710   
9       CA-2014-115812   9/06/2014  14/06/2014  Standard Class    BH-11710   
10      CA-2014-115812   9/06/2014  14/06/2014  Standard Class    BH-11710   

          Customer Name    Segment        Country             C

# Read Data from an Excel

In [33]:
file_path_1 = r"C:\Users\jimrb\OneDrive\Documents\MyProjects\mypython github\Datasets\Superstore.xls"
sheet_name = "Returns"

def get_df_from_excel(file_name_1, sheet_name):
    try:
        df_1 = pd.read_excel(file_path_1, sheet_name)
    except FileNotFoundError:
        pass
    else:
        return df_1

In [32]:
df_1 = pd.read_excel(file_path_1)

if df_1 is not None:
    print(df_1.head(10))
else:
    print("File not found.")

   Row ID        Order ID Order Date  Ship Date       Ship Mode Customer ID  \
0       1  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520   
1       2  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520   
2       3  CA-2016-138688 2016-06-12 2016-06-16    Second Class    DV-13045   
3       4  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335   
4       5  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335   
5       6  CA-2014-115812 2014-06-09 2014-06-14  Standard Class    BH-11710   
6       7  CA-2014-115812 2014-06-09 2014-06-14  Standard Class    BH-11710   
7       8  CA-2014-115812 2014-06-09 2014-06-14  Standard Class    BH-11710   
8       9  CA-2014-115812 2014-06-09 2014-06-14  Standard Class    BH-11710   
9      10  CA-2014-115812 2014-06-09 2014-06-14  Standard Class    BH-11710   

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderso

# Read Data from HTML

In [34]:
URL = "https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population"
# Exclude columns with the index 0 and 6
exclude_column = [0,6]
# Extract table with the index 0
html_data = pd.read_html(URL)[0]

# Use the drop method with columns argument to exclude the column by index
html_data = html_data.drop(columns=html_data.columns[exclude_column])

# Now, the specified column by index is removed from 'html_data'
html_data

Country / Dependency  Population % of world         Date  \
0                                  World  8063128000       100%   1 Oct 2023   
1                                  China  1411750000        NaN  31 Dec 2022   
2                                  India  1392329000        NaN   1 Mar 2023   
3                          United States   335447000        NaN   1 Oct 2023   
4                              Indonesia   278696200        NaN   1 Jul 2023   
..                                   ...         ...        ...          ...   
237                         Tokelau (NZ)        1647        NaN   1 Jan 2019   
238                                 Niue        1549        NaN   1 Jul 2021   
239                         Vatican City         764        NaN  26 Jun 2023   
240  Cocos (Keeling) Islands (Australia)         593        NaN  30 Jun 2020   
241                Pitcairn Islands (UK)          47        NaN   1 Jul 2021   

    Source (official or from the United Nations)  
0                               UN projection[3]  
1                           Official estimate[4]  
2                         Official projection[5]  
3                   National population clock[7]  
4                  National annual projection[8]  
..                                           ...  
237                            2019 Census [230]  
238              National annual projection[182]  
239                         Official figure[231]  
240                             2021 Census[232]  
241                       Official estimate[233]  

[242 rows x 5 columns]